languageCode = "en"
languageName = "English"
weight = 1
title = "KilobyteKeith"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"
logo = "img/nes-by-smashicons.png"
secondaryLogo = "img/sega-by-smashicons.png"
description = "KilobyteKeith on Twitch"
copyright = 'Made with &#9829; by <a href="https://binarydigit.city">BinaryDigit</a>'

[params.author]
name = "I'm Keith!"
email = "KilobyteKeith@gmail.com"
image = "img/KeithAvatar.png"
headline = "I'm an internet boomer who loves playing retro, horror, and FPS games. Jugs of Arnold Palmer and a never-ending tech obsession give me life! I’ve got two awesome dogs, Luna and Pixel that usually pop in. Come hang out for fun games and geeky conversations!"
bio = "Retro Variety Streamer, Chill Dude, First-Person Potato, Flannel Enthusiast, Foodie, and Covered in Dog Hair"
links = [
    { envelope = "mailto:kilobytekeith@gmail.com" },
    { twitch = "https://twitch.tv/kilobytekeith" },
    { link = "https://shop.kilobytekeith.com" },
    { bluesky = "https://bsky.app/profile/kilobytekeith.tv" },
    { instagram = "https://www.instagram.com/kilobytekeithtv/" },
    { youtube = "https://www.youtube.com/@kilobytekeith" },
    { discord = "/discord" }
]